#!/usr/bin/with-contenv sh

exec /usr/sbin/dnsmasq --user=root --domain-needed --interface=lo --listen-address=127.0.0.1 --bind-interfaces --local-ttl=2 --neg-ttl=0 --max-ttl=2 --max-cache-ttl=2 --min-cache-ttl=1 --auth-ttl=2 --dhcp-ttl=2 -k;
